import type { Analysis, Industry, Priority, SolutionArea } from './types'

export const SEED_ANALYSES: Analysis[] = [
  {
    id: 'seed-1',
    createdAt: Date.now() - 86400000 * 30,
    updatedAt: Date.now() - 86400000 * 30,
    projectBasics: {
      name: 'AI-Powered Customer Service Platform',
      customerName: 'FirstBank International',
      subsidiary: 'South Africa Subsidiary',
      region: 'MEA (Middle East & Africa)',
      description: 'Deploy an AI chatbot to handle 70% of customer queries, reducing call center costs and improving response times.',
      industry: 'banking' as Industry,
      solutionArea: 'AI Business Solutions' as SolutionArea,
      solutionAreas: ['AI Business Solutions', 'Cloud & AI Platforms'] as SolutionArea[],
      investmentAmount: 850000,
      timelineMonths: 18,
    },
    baselineMetrics: {
      currentRevenue: 45000000,
      currentCosts: 22000000,
      employeeCount: 450,
      currentAssets: 120000000,
      currentCashFlow: 18000000,
    },
    impactProjections: {
      revenueGrowthRate: 12,
      costReduction: 28,
      efficiencyGain: 35,
      timeToMarketImprovement: 20,
    },
    strategicFactors: {
      competitiveDifferentiation: 4,
      riskMitigation: 5,
      customerExperience: 5,
      employeeProductivity: 4,
      regulatoryCompliance: 3,
      innovationEnablement: 4,
    },
    results: {
      conservative: {
        roi: 145,
        npv: 1234500,
        paybackMonths: 14.5,
        revenueImpact: 540000,
        costSavings: 6160000,
        netBenefit: 5850000,
      },
      realistic: {
        roi: 185,
        npv: 1572500,
        paybackMonths: 11.2,
        revenueImpact: 540000,
        costSavings: 6160000,
        netBenefit: 5850000,
      },
      optimistic: {
        roi: 225,
        npv: 1912500,
        paybackMonths: 9.1,
        revenueImpact: 540000,
        costSavings: 6160000,
        netBenefit: 5850000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'critical' as Priority,
      reasoning: 'High ROI with significant cost savings and customer experience improvements. Strong strategic alignment.',
      nextSteps: [
        'Secure executive sponsorship',
        'Conduct vendor evaluation',
        'Design phased rollout plan',
      ],
      successMetrics: [
        'First contact resolution rate > 80%',
        'Average handling time reduced by 40%',
        'Customer satisfaction score > 4.5/5',
      ],
      risks: [
        'Integration complexity with legacy systems',
        'Change management resistance',
        'Data privacy compliance requirements',
      ],
    },
  },
  {
    id: 'seed-2',
    createdAt: Date.now() - 86400000 * 25,
    updatedAt: Date.now() - 86400000 * 25,
    projectBasics: {
      name: 'Cloud Migration - Core Banking Platform',
      customerName: 'FirstBank International',
      subsidiary: 'Kenya Subsidiary',
      region: 'MEA (Middle East & Africa)',
      description: 'Migrate core banking systems to cloud infrastructure for improved scalability and disaster recovery.',
      industry: 'banking' as Industry,
      solutionArea: 'Cloud & AI Platforms' as SolutionArea,
      solutionAreas: ['Cloud & AI Platforms', 'Security'] as SolutionArea[],
      investmentAmount: 2500000,
      timelineMonths: 24,
    },
    baselineMetrics: {
      currentRevenue: 45000000,
      currentCosts: 22000000,
      employeeCount: 450,
      currentAssets: 120000000,
      currentCashFlow: 18000000,
    },
    impactProjections: {
      revenueGrowthRate: 8,
      costReduction: 22,
      efficiencyGain: 40,
      timeToMarketImprovement: 45,
    },
    strategicFactors: {
      competitiveDifferentiation: 5,
      riskMitigation: 5,
      customerExperience: 4,
      employeeProductivity: 4,
      regulatoryCompliance: 5,
      innovationEnablement: 5,
    },
    results: {
      conservative: {
        roi: 98,
        npv: 2450000,
        paybackMonths: 22.5,
        revenueImpact: 3600000,
        costSavings: 4840000,
        netBenefit: 5940000,
      },
      realistic: {
        roi: 135,
        npv: 3375000,
        paybackMonths: 17.8,
        revenueImpact: 3600000,
        costSavings: 4840000,
        netBenefit: 5940000,
      },
      optimistic: {
        roi: 172,
        npv: 4300000,
        paybackMonths: 14.2,
        revenueImpact: 3600000,
        costSavings: 4840000,
        netBenefit: 5940000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'critical' as Priority,
      reasoning: 'Essential for future innovation and scalability. Strong cost savings and risk mitigation benefits.',
      nextSteps: [
        'Select cloud provider',
        'Develop migration roadmap',
        'Establish DevOps practices',
      ],
      successMetrics: [
        'Infrastructure costs reduced by 25%',
        'System availability > 99.9%',
        'New feature deployment time < 2 weeks',
      ],
      risks: [
        'Migration complexity and downtime',
        'Security and compliance challenges',
        'Vendor lock-in concerns',
      ],
    },
  },
  {
    id: 'seed-3',
    createdAt: Date.now() - 86400000 * 20,
    updatedAt: Date.now() - 86400000 * 20,
    projectBasics: {
      name: 'Predictive Maintenance System',
      customerName: 'AutoManufacture Corp',
      subsidiary: 'Netherlands Subsidiary',
      region: 'North Europe',
      description: 'IoT sensors and ML algorithms to predict equipment failures before they occur, reducing downtime.',
      industry: 'manufacturing' as Industry,
      solutionArea: 'AI Business Solutions' as SolutionArea,
      solutionAreas: ['AI Business Solutions', 'Cloud & AI Platforms'] as SolutionArea[],
      investmentAmount: 1200000,
      timelineMonths: 15,
    },
    baselineMetrics: {
      currentRevenue: 120000000,
      currentCosts: 85000000,
      employeeCount: 850,
      currentAssets: 250000000,
      currentCashFlow: 28000000,
    },
    impactProjections: {
      revenueGrowthRate: 5,
      costReduction: 18,
      efficiencyGain: 30,
      timeToMarketImprovement: 10,
    },
    strategicFactors: {
      competitiveDifferentiation: 4,
      riskMitigation: 5,
      customerExperience: 3,
      employeeProductivity: 4,
      regulatoryCompliance: 4,
      innovationEnablement: 5,
    },
    results: {
      conservative: {
        roi: 168,
        npv: 2016000,
        paybackMonths: 12.8,
        revenueImpact: 6000000,
        costSavings: 15300000,
        netBenefit: 20100000,
      },
      realistic: {
        roi: 210,
        npv: 2520000,
        paybackMonths: 10.2,
        revenueImpact: 6000000,
        costSavings: 15300000,
        netBenefit: 20100000,
      },
      optimistic: {
        roi: 252,
        npv: 3024000,
        paybackMonths: 8.5,
        revenueImpact: 6000000,
        costSavings: 15300000,
        netBenefit: 20100000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'high' as Priority,
      reasoning: 'Strong ROI through reduced downtime and maintenance costs. Enables data-driven operations.',
      nextSteps: [
        'Install IoT sensor infrastructure',
        'Build ML model training pipeline',
        'Train maintenance teams on new processes',
      ],
      successMetrics: [
        'Unplanned downtime reduced by 35%',
        'Maintenance costs reduced by 20%',
        'Equipment OEE improved by 15%',
      ],
      risks: [
        'Sensor installation complexity',
        'Data quality and connectivity issues',
        'Model accuracy requirements',
      ],
    },
  },
  {
    id: 'seed-4',
    createdAt: Date.now() - 86400000 * 15,
    updatedAt: Date.now() - 86400000 * 15,
    projectBasics: {
      name: 'E-commerce Platform Modernization',
      customerName: 'RetailGlobal Inc',
      subsidiary: 'UK Subsidiary',
      region: 'North Europe',
      description: 'Rebuild e-commerce platform with modern architecture, personalization, and mobile-first design.',
      industry: 'retail' as Industry,
      solutionArea: 'AI Business Solutions' as SolutionArea,
      investmentAmount: 3200000,
      timelineMonths: 20,
    },
    baselineMetrics: {
      currentRevenue: 95000000,
      currentCosts: 62000000,
      employeeCount: 620,
      currentAssets: 85000000,
      currentCashFlow: 24000000,
    },
    impactProjections: {
      revenueGrowthRate: 25,
      costReduction: 12,
      efficiencyGain: 35,
      timeToMarketImprovement: 50,
    },
    strategicFactors: {
      competitiveDifferentiation: 5,
      riskMitigation: 3,
      customerExperience: 5,
      employeeProductivity: 4,
      regulatoryCompliance: 3,
      innovationEnablement: 5,
    },
    results: {
      conservative: {
        roi: 215,
        npv: 6880000,
        paybackMonths: 13.5,
        revenueImpact: 23750000,
        costSavings: 7440000,
        netBenefit: 27990000,
      },
      realistic: {
        roi: 268,
        npv: 8576000,
        paybackMonths: 10.7,
        revenueImpact: 23750000,
        costSavings: 7440000,
        netBenefit: 27990000,
      },
      optimistic: {
        roi: 322,
        npv: 10304000,
        paybackMonths: 8.9,
        revenueImpact: 23750000,
        costSavings: 7440000,
        netBenefit: 27990000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'critical' as Priority,
      reasoning: 'Exceptional revenue growth potential with strong customer experience improvements. Critical for competitive positioning.',
      nextSteps: [
        'Finalize technical architecture',
        'Select implementation partner',
        'Design phased migration strategy',
      ],
      successMetrics: [
        'Conversion rate improved by 40%',
        'Mobile revenue > 60% of total',
        'Page load times < 2 seconds',
      ],
      risks: [
        'Migration complexity and SEO impact',
        'Integration with existing systems',
        'Timeline and budget overruns',
      ],
    },
  },
  {
    id: 'seed-5',
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now() - 86400000 * 10,
    projectBasics: {
      name: 'DevOps Automation Platform',
      customerName: 'TechVentures Ltd',
      subsidiary: 'USA Subsidiary',
      region: 'Americas',
      description: 'Implement CI/CD pipelines, infrastructure as code, and automated testing to accelerate delivery.',
      industry: 'technology' as Industry,
      solutionArea: 'AI Business Solutions' as SolutionArea,
      investmentAmount: 450000,
      timelineMonths: 10,
    },
    baselineMetrics: {
      currentRevenue: 28000000,
      currentCosts: 19000000,
      employeeCount: 185,
      currentAssets: 45000000,
      currentCashFlow: 7500000,
    },
    impactProjections: {
      revenueGrowthRate: 15,
      costReduction: 20,
      efficiencyGain: 45,
      timeToMarketImprovement: 60,
    },
    strategicFactors: {
      competitiveDifferentiation: 4,
      riskMitigation: 4,
      customerExperience: 4,
      employeeProductivity: 5,
      regulatoryCompliance: 3,
      innovationEnablement: 5,
    },
    results: {
      conservative: {
        roi: 245,
        npv: 1102500,
        paybackMonths: 9.5,
        revenueImpact: 4200000,
        costSavings: 3800000,
        netBenefit: 7550000,
      },
      realistic: {
        roi: 306,
        npv: 1377000,
        paybackMonths: 7.6,
        revenueImpact: 4200000,
        costSavings: 3800000,
        netBenefit: 7550000,
      },
      optimistic: {
        roi: 367,
        npv: 1651500,
        paybackMonths: 6.3,
        revenueImpact: 4200000,
        costSavings: 3800000,
        netBenefit: 7550000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'high' as Priority,
      reasoning: 'Excellent ROI with transformative impact on development velocity and quality. Quick payback period.',
      nextSteps: [
        'Select toolchain and platforms',
        'Train development teams',
        'Migrate pilot projects first',
      ],
      successMetrics: [
        'Deployment frequency > 10x per day',
        'Lead time for changes < 1 hour',
        'Change failure rate < 5%',
      ],
      risks: [
        'Learning curve for teams',
        'Tool integration complexity',
        'Cultural resistance to change',
      ],
    },
  },
  {
    id: 'seed-6',
    createdAt: Date.now() - 86400000 * 8,
    updatedAt: Date.now() - 86400000 * 8,
    projectBasics: {
      name: 'Supply Chain Visibility Platform',
      customerName: 'AutoManufacture Corp',
      subsidiary: 'Netherlands Subsidiary',
      region: 'North Europe',
      description: 'Real-time tracking and analytics for end-to-end supply chain visibility and optimization.',
      industry: 'manufacturing' as Industry,
      solutionArea: 'Cloud & AI Platforms' as SolutionArea,
      investmentAmount: 1800000,
      timelineMonths: 16,
    },
    baselineMetrics: {
      currentRevenue: 120000000,
      currentCosts: 85000000,
      employeeCount: 850,
      currentAssets: 250000000,
      currentCashFlow: 28000000,
    },
    impactProjections: {
      revenueGrowthRate: 8,
      costReduction: 15,
      efficiencyGain: 28,
      timeToMarketImprovement: 25,
    },
    strategicFactors: {
      competitiveDifferentiation: 4,
      riskMitigation: 5,
      customerExperience: 4,
      employeeProductivity: 4,
      regulatoryCompliance: 3,
      innovationEnablement: 4,
    },
    results: {
      conservative: {
        roi: 142,
        npv: 2556000,
        paybackMonths: 15.2,
        revenueImpact: 9600000,
        costSavings: 12750000,
        netBenefit: 20550000,
      },
      realistic: {
        roi: 178,
        npv: 3204000,
        paybackMonths: 12.1,
        revenueImpact: 9600000,
        costSavings: 12750000,
        netBenefit: 20550000,
      },
      optimistic: {
        roi: 213,
        npv: 3834000,
        paybackMonths: 10.1,
        revenueImpact: 9600000,
        costSavings: 12750000,
        netBenefit: 20550000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'high' as Priority,
      reasoning: 'Strong cost reduction and risk mitigation benefits. Improves resilience and agility.',
      nextSteps: [
        'Map current supply chain processes',
        'Select platform vendor',
        'Onboard key suppliers and partners',
      ],
      successMetrics: [
        'Inventory carrying costs reduced by 20%',
        'Supply chain cycle time reduced by 30%',
        'On-time delivery rate > 95%',
      ],
      risks: [
        'Supplier integration challenges',
        'Data standardization complexity',
        'Network connectivity requirements',
      ],
    },
  },
  {
    id: 'seed-7',
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 5,
    projectBasics: {
      name: 'Mobile Banking App Redesign',
      customerName: 'FirstBank International',
      subsidiary: 'Nigeria Subsidiary',
      region: 'MEA (Middle East & Africa)',
      description: 'Complete redesign of mobile banking app with enhanced UX, biometric auth, and new digital services.',
      industry: 'banking' as Industry,
      solutionArea: 'AI Business Solutions' as SolutionArea,
      investmentAmount: 650000,
      timelineMonths: 12,
    },
    baselineMetrics: {
      currentRevenue: 45000000,
      currentCosts: 22000000,
      employeeCount: 450,
      currentAssets: 120000000,
      currentCashFlow: 18000000,
    },
    impactProjections: {
      revenueGrowthRate: 18,
      costReduction: 10,
      efficiencyGain: 25,
      timeToMarketImprovement: 15,
    },
    strategicFactors: {
      competitiveDifferentiation: 5,
      riskMitigation: 3,
      customerExperience: 5,
      employeeProductivity: 3,
      regulatoryCompliance: 4,
      innovationEnablement: 4,
    },
    results: {
      conservative: {
        roi: 198,
        npv: 1287000,
        paybackMonths: 11.8,
        revenueImpact: 8100000,
        costSavings: 2200000,
        netBenefit: 9650000,
      },
      realistic: {
        roi: 248,
        npv: 1612000,
        paybackMonths: 9.4,
        revenueImpact: 8100000,
        costSavings: 2200000,
        netBenefit: 9650000,
      },
      optimistic: {
        roi: 297,
        npv: 1930500,
        paybackMonths: 7.8,
        revenueImpact: 8100000,
        costSavings: 2200000,
        netBenefit: 9650000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'high' as Priority,
      reasoning: 'High customer demand with strong revenue growth potential. Critical for mobile-first strategy.',
      nextSteps: [
        'Conduct user research and testing',
        'Design new information architecture',
        'Develop MVP feature set',
      ],
      successMetrics: [
        'Mobile active users increased by 50%',
        'App store rating > 4.5 stars',
        'Digital transaction volume up 60%',
      ],
      risks: [
        'User adoption and migration challenges',
        'Platform compatibility issues',
        'Security and fraud concerns',
      ],
    },
  },
  {
    id: 'seed-8',
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now() - 86400000 * 3,
    projectBasics: {
      name: 'Customer Data Platform',
      customerName: 'RetailGlobal Inc',
      subsidiary: 'Sweden Subsidiary',
      region: 'North Europe',
      description: 'Unified customer data platform for personalization, segmentation, and omnichannel marketing.',
      industry: 'retail' as Industry,
      solutionArea: 'Cloud & AI Platforms' as SolutionArea,
      investmentAmount: 980000,
      timelineMonths: 14,
    },
    baselineMetrics: {
      currentRevenue: 95000000,
      currentCosts: 62000000,
      employeeCount: 620,
      currentAssets: 85000000,
      currentCashFlow: 24000000,
    },
    impactProjections: {
      revenueGrowthRate: 22,
      costReduction: 8,
      efficiencyGain: 20,
      timeToMarketImprovement: 30,
    },
    strategicFactors: {
      competitiveDifferentiation: 5,
      riskMitigation: 3,
      customerExperience: 5,
      employeeProductivity: 4,
      regulatoryCompliance: 4,
      innovationEnablement: 4,
    },
    results: {
      conservative: {
        roi: 312,
        npv: 3057600,
        paybackMonths: 8.2,
        revenueImpact: 20900000,
        costSavings: 4960000,
        netBenefit: 24880000,
      },
      realistic: {
        roi: 390,
        npv: 3822000,
        paybackMonths: 6.6,
        revenueImpact: 20900000,
        costSavings: 4960000,
        netBenefit: 24880000,
      },
      optimistic: {
        roi: 468,
        npv: 4586400,
        paybackMonths: 5.5,
        revenueImpact: 20900000,
        costSavings: 4960000,
        netBenefit: 24880000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'critical' as Priority,
      reasoning: 'Exceptional ROI with transformative impact on marketing effectiveness and customer lifetime value.',
      nextSteps: [
        'Define data governance framework',
        'Select CDP platform',
        'Design customer journey maps',
      ],
      successMetrics: [
        'Marketing ROI improved by 45%',
        'Customer lifetime value up 30%',
        'Campaign conversion rates up 35%',
      ],
      risks: [
        'Data integration and quality challenges',
        'Privacy and GDPR compliance',
        'Organizational silos and data ownership',
      ],
    },
  },
  {
    id: 'seed-9',
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000 * 2,
    projectBasics: {
      name: 'Microservices Architecture Migration',
      customerName: 'TechVentures Ltd',
      subsidiary: 'USA Subsidiary',
      region: 'Americas',
      description: 'Decompose monolithic application into microservices for improved scalability and development velocity.',
      industry: 'technology' as Industry,
      solutionArea: 'Cloud & AI Platforms' as SolutionArea,
      investmentAmount: 1500000,
      timelineMonths: 22,
    },
    baselineMetrics: {
      currentRevenue: 28000000,
      currentCosts: 19000000,
      employeeCount: 185,
      currentAssets: 45000000,
      currentCashFlow: 7500000,
    },
    impactProjections: {
      revenueGrowthRate: 12,
      costReduction: 15,
      efficiencyGain: 40,
      timeToMarketImprovement: 55,
    },
    strategicFactors: {
      competitiveDifferentiation: 4,
      riskMitigation: 4,
      customerExperience: 4,
      employeeProductivity: 5,
      regulatoryCompliance: 3,
      innovationEnablement: 5,
    },
    results: {
      conservative: {
        roi: 88,
        npv: 1320000,
        paybackMonths: 24.5,
        revenueImpact: 3360000,
        costSavings: 2850000,
        netBenefit: 4710000,
      },
      realistic: {
        roi: 110,
        npv: 1650000,
        paybackMonths: 19.6,
        revenueImpact: 3360000,
        costSavings: 2850000,
        netBenefit: 4710000,
      },
      optimistic: {
        roi: 132,
        npv: 1980000,
        paybackMonths: 16.3,
        revenueImpact: 3360000,
        costSavings: 2850000,
        netBenefit: 4710000,
      },
    },
    recommendation: {
      decision: 'conditional',
      priority: 'medium' as Priority,
      reasoning: 'Moderate ROI with long payback period. Recommended only if current architecture is severely limiting growth.',
      nextSteps: [
        'Assess current technical debt',
        'Define service boundaries',
        'Establish observability framework',
      ],
      successMetrics: [
        'Service deployment independence achieved',
        'Mean time to recovery < 30 minutes',
        'Feature delivery throughput up 50%',
      ],
      risks: [
        'Significant complexity increase',
        'Distributed system debugging challenges',
        'Team skill gaps and learning curve',
      ],
    },
  },
  {
    id: 'seed-10',
    createdAt: Date.now() - 86400000 * 1,
    updatedAt: Date.now() - 86400000 * 1,
    projectBasics: {
      name: 'Robotic Process Automation (RPA)',
      customerName: 'FirstBank International',
      subsidiary: 'UAE Subsidiary',
      region: 'MEA (Middle East & Africa)',
      description: 'Deploy RPA bots to automate repetitive back-office processes including data entry and reconciliation.',
      industry: 'banking' as Industry,
      solutionArea: 'AI Business Solutions' as SolutionArea,
      investmentAmount: 380000,
      timelineMonths: 9,
    },
    baselineMetrics: {
      currentRevenue: 45000000,
      currentCosts: 22000000,
      employeeCount: 450,
      currentAssets: 120000000,
      currentCashFlow: 18000000,
    },
    impactProjections: {
      revenueGrowthRate: 3,
      costReduction: 32,
      efficiencyGain: 50,
      timeToMarketImprovement: 5,
    },
    strategicFactors: {
      competitiveDifferentiation: 2,
      riskMitigation: 4,
      customerExperience: 3,
      employeeProductivity: 5,
      regulatoryCompliance: 4,
      innovationEnablement: 3,
    },
    results: {
      conservative: {
        roi: 278,
        npv: 1056400,
        paybackMonths: 7.8,
        revenueImpact: 1350000,
        costSavings: 7040000,
        netBenefit: 8010000,
      },
      realistic: {
        roi: 348,
        npv: 1322400,
        paybackMonths: 6.2,
        revenueImpact: 1350000,
        costSavings: 7040000,
        netBenefit: 8010000,
      },
      optimistic: {
        roi: 417,
        npv: 1584600,
        paybackMonths: 5.2,
        revenueImpact: 1350000,
        costSavings: 7040000,
        netBenefit: 8010000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'high' as Priority,
      reasoning: 'Excellent ROI with quick payback. High cost reduction and productivity gains with relatively low risk.',
      nextSteps: [
        'Identify highest-impact processes',
        'Select RPA platform and vendor',
        'Build center of excellence',
      ],
      successMetrics: [
        'Process completion time reduced by 70%',
        'Error rates reduced by 90%',
        '40 FTE hours freed for higher-value work',
      ],
      risks: [
        'Process change management',
        'Bot maintenance and monitoring',
        'Integration with legacy systems',
      ],
    },
  },
  {
    id: 'seed-11',
    createdAt: Date.now() - 86400000 * 6,
    updatedAt: Date.now() - 86400000 * 6,
    projectBasics: {
      name: 'Inventory Optimization System',
      customerName: 'RetailGlobal Inc',
      subsidiary: 'Spain Subsidiary',
      region: 'South Europe',
      description: 'AI-powered demand forecasting and inventory optimization to reduce stockouts and overstock.',
      industry: 'retail' as Industry,
      solutionArea: 'AI Business Solutions' as SolutionArea,
      investmentAmount: 720000,
      timelineMonths: 13,
    },
    baselineMetrics: {
      currentRevenue: 95000000,
      currentCosts: 62000000,
      employeeCount: 620,
      currentAssets: 85000000,
      currentCashFlow: 24000000,
    },
    impactProjections: {
      revenueGrowthRate: 10,
      costReduction: 20,
      efficiencyGain: 32,
      timeToMarketImprovement: 8,
    },
    strategicFactors: {
      competitiveDifferentiation: 3,
      riskMitigation: 4,
      customerExperience: 4,
      employeeProductivity: 4,
      regulatoryCompliance: 2,
      innovationEnablement: 4,
    },
    results: {
      conservative: {
        roi: 268,
        npv: 1929600,
        paybackMonths: 8.9,
        revenueImpact: 9500000,
        costSavings: 12400000,
        netBenefit: 21180000,
      },
      realistic: {
        roi: 335,
        npv: 2412000,
        paybackMonths: 7.1,
        revenueImpact: 9500000,
        costSavings: 12400000,
        netBenefit: 21180000,
      },
      optimistic: {
        roi: 402,
        npv: 2894400,
        paybackMonths: 5.9,
        revenueImpact: 9500000,
        costSavings: 12400000,
        netBenefit: 21180000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'high' as Priority,
      reasoning: 'Strong ROI with significant working capital benefits. Improves customer satisfaction and reduces waste.',
      nextSteps: [
        'Clean and prepare historical data',
        'Select forecasting platform',
        'Pilot in select product categories',
      ],
      successMetrics: [
        'Inventory turnover improved by 25%',
        'Stockout rate reduced by 40%',
        'Working capital freed up by $8M',
      ],
      risks: [
        'Data quality and availability',
        'Integration with merchandising systems',
        'Change management with buyers',
      ],
    },
  },
  {
    id: 'seed-12',
    createdAt: Date.now() - 86400000 * 12,
    updatedAt: Date.now() - 86400000 * 12,
    projectBasics: {
      name: 'Quality Assurance Automation',
      customerName: 'AutoManufacture Corp',
      subsidiary: 'Belgium Subsidiary',
      region: 'North Europe',
      description: 'Computer vision and robotics for automated quality inspection, reducing defects and rework.',
      industry: 'manufacturing' as Industry,
      solutionArea: 'AI Business Solutions' as SolutionArea,
      investmentAmount: 2800000,
      timelineMonths: 18,
    },
    baselineMetrics: {
      currentRevenue: 120000000,
      currentCosts: 85000000,
      employeeCount: 850,
      currentAssets: 250000000,
      currentCashFlow: 28000000,
    },
    impactProjections: {
      revenueGrowthRate: 6,
      costReduction: 25,
      efficiencyGain: 35,
      timeToMarketImprovement: 12,
    },
    strategicFactors: {
      competitiveDifferentiation: 4,
      riskMitigation: 5,
      customerExperience: 5,
      employeeProductivity: 4,
      regulatoryCompliance: 5,
      innovationEnablement: 4,
    },
    results: {
      conservative: {
        roi: 152,
        npv: 4256000,
        paybackMonths: 14.2,
        revenueImpact: 7200000,
        costSavings: 21250000,
        netBenefit: 25650000,
      },
      realistic: {
        roi: 190,
        npv: 5320000,
        paybackMonths: 11.3,
        revenueImpact: 7200000,
        costSavings: 21250000,
        netBenefit: 25650000,
      },
      optimistic: {
        roi: 228,
        npv: 6384000,
        paybackMonths: 9.4,
        revenueImpact: 7200000,
        costSavings: 21250000,
        netBenefit: 25650000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'critical' as Priority,
      reasoning: 'Strong financial returns with critical quality and compliance benefits. Reduces warranty costs and improves brand reputation.',
      nextSteps: [
        'Design inspection workflow',
        'Select vision system vendor',
        'Train AI models on defect data',
      ],
      successMetrics: [
        'Defect detection rate > 99.5%',
        'Rework costs reduced by 60%',
        'Customer quality complaints down 50%',
      ],
      risks: [
        'Integration with production line',
        'Model training data requirements',
        'Lighting and environment variability',
      ],
    },
  },
  {
    id: 'seed-13',
    createdAt: Date.now() - 86400000 * 18,
    updatedAt: Date.now() - 86400000 * 18,
    projectBasics: {
      name: 'Real-Time Analytics Dashboard',
      customerName: 'TechVentures Ltd',
      subsidiary: 'Canada Subsidiary',
      region: 'Americas',
      description: 'Executive dashboard with real-time business metrics, predictive analytics, and anomaly detection.',
      industry: 'technology' as Industry,
      solutionArea: 'Cloud & AI Platforms' as SolutionArea,
      investmentAmount: 280000,
      timelineMonths: 8,
    },
    baselineMetrics: {
      currentRevenue: 28000000,
      currentCosts: 19000000,
      employeeCount: 185,
      currentAssets: 45000000,
      currentCashFlow: 7500000,
    },
    impactProjections: {
      revenueGrowthRate: 8,
      costReduction: 5,
      efficiencyGain: 15,
      timeToMarketImprovement: 10,
    },
    strategicFactors: {
      competitiveDifferentiation: 2,
      riskMitigation: 3,
      customerExperience: 2,
      employeeProductivity: 4,
      regulatoryCompliance: 2,
      innovationEnablement: 3,
    },
    results: {
      conservative: {
        roi: 118,
        npv: 330400,
        paybackMonths: 18.2,
        revenueImpact: 2240000,
        costSavings: 950000,
        netBenefit: 2910000,
      },
      realistic: {
        roi: 148,
        npv: 414400,
        paybackMonths: 14.5,
        revenueImpact: 2240000,
        costSavings: 950000,
        netBenefit: 2910000,
      },
      optimistic: {
        roi: 177,
        npv: 495600,
        paybackMonths: 12.1,
        revenueImpact: 2240000,
        costSavings: 950000,
        netBenefit: 2910000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'medium' as Priority,
      reasoning: 'Moderate ROI but improves decision-making speed and quality. Enables data-driven culture.',
      nextSteps: [
        'Define key metrics and KPIs',
        'Select BI platform',
        'Design role-based views',
      ],
      successMetrics: [
        'Decision cycle time reduced by 40%',
        'Issue detection time < 4 hours',
        'Dashboard adoption by all executives',
      ],
      risks: [
        'Data source integration complexity',
        'Metric definition alignment',
        'User adoption and training',
      ],
    },
  },
  {
    id: 'seed-14',
    createdAt: Date.now() - 86400000 * 22,
    updatedAt: Date.now() - 86400000 * 22,
    projectBasics: {
      name: 'Fraud Detection System',
      customerName: 'FirstBank International',
      subsidiary: 'Qatar Subsidiary',
      region: 'MEA (Middle East & Africa)',
      description: 'Machine learning-based fraud detection for transactions, reducing losses and false positives.',
      industry: 'banking' as Industry,
      solutionArea: 'AI Business Solutions' as SolutionArea,
      investmentAmount: 1100000,
      timelineMonths: 14,
    },
    baselineMetrics: {
      currentRevenue: 45000000,
      currentCosts: 22000000,
      employeeCount: 450,
      currentAssets: 120000000,
      currentCashFlow: 18000000,
    },
    impactProjections: {
      revenueGrowthRate: 5,
      costReduction: 35,
      efficiencyGain: 40,
      timeToMarketImprovement: 5,
    },
    strategicFactors: {
      competitiveDifferentiation: 3,
      riskMitigation: 5,
      customerExperience: 4,
      employeeProductivity: 4,
      regulatoryCompliance: 5,
      innovationEnablement: 3,
    },
    results: {
      conservative: {
        roi: 195,
        npv: 2145000,
        paybackMonths: 11.5,
        revenueImpact: 2250000,
        costSavings: 7700000,
        netBenefit: 8850000,
      },
      realistic: {
        roi: 244,
        npv: 2684000,
        paybackMonths: 9.2,
        revenueImpact: 2250000,
        costSavings: 7700000,
        netBenefit: 8850000,
      },
      optimistic: {
        roi: 293,
        npv: 3223000,
        paybackMonths: 7.7,
        revenueImpact: 2250000,
        costSavings: 7700000,
        netBenefit: 8850000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'critical' as Priority,
      reasoning: 'Critical for risk management with strong ROI. Reduces fraud losses while improving customer experience.',
      nextSteps: [
        'Prepare training data sets',
        'Select ML platform and models',
        'Design alert and investigation workflow',
      ],
      successMetrics: [
        'Fraud losses reduced by 65%',
        'False positive rate < 5%',
        'Detection time < 1 second',
      ],
      risks: [
        'Model accuracy and bias',
        'Real-time processing requirements',
        'Regulatory approval process',
      ],
    },
  },
  {
    id: 'seed-15',
    createdAt: Date.now() - 86400000 * 28,
    updatedAt: Date.now() - 86400000 * 28,
    projectBasics: {
      name: 'Personalization Engine',
      customerName: 'RetailGlobal Inc',
      subsidiary: 'Italy Subsidiary',
      region: 'South Europe',
      description: 'AI-powered product recommendations and personalized shopping experiences across all channels.',
      industry: 'retail' as Industry,
      solutionArea: 'AI Business Solutions' as SolutionArea,
      investmentAmount: 890000,
      timelineMonths: 11,
    },
    baselineMetrics: {
      currentRevenue: 95000000,
      currentCosts: 62000000,
      employeeCount: 620,
      currentAssets: 85000000,
      currentCashFlow: 24000000,
    },
    impactProjections: {
      revenueGrowthRate: 28,
      costReduction: 6,
      efficiencyGain: 18,
      timeToMarketImprovement: 12,
    },
    strategicFactors: {
      competitiveDifferentiation: 5,
      riskMitigation: 2,
      customerExperience: 5,
      employeeProductivity: 3,
      regulatoryCompliance: 3,
      innovationEnablement: 4,
    },
    results: {
      conservative: {
        roi: 368,
        npv: 3275200,
        paybackMonths: 6.8,
        revenueImpact: 26600000,
        costSavings: 3720000,
        netBenefit: 29431000,
      },
      realistic: {
        roi: 460,
        npv: 4094000,
        paybackMonths: 5.4,
        revenueImpact: 26600000,
        costSavings: 3720000,
        netBenefit: 29431000,
      },
      optimistic: {
        roi: 552,
        npv: 4912800,
        paybackMonths: 4.5,
        revenueImpact: 26600000,
        costSavings: 3720000,
        netBenefit: 29431000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'critical' as Priority,
      reasoning: 'Exceptional ROI with transformative revenue impact. Critical competitive differentiator in digital retail.',
      nextSteps: [
        'Collect and enrich customer behavioral data',
        'Select recommendation engine',
        'A/B test recommendation strategies',
      ],
      successMetrics: [
        'Average order value up 35%',
        'Cross-sell rate improved by 50%',
        'Customer engagement time up 40%',
      ],
      risks: [
        'Cold start problem for new customers',
        'Privacy and data usage concerns',
        'Algorithm transparency requirements',
      ],
    },
  },
  {
    id: 'seed-16',
    createdAt: Date.now() - 86400000 * 32,
    updatedAt: Date.now() - 86400000 * 32,
    projectBasics: {
      name: 'Digital Wallet Platform',
      customerName: 'FirstBank International',
      subsidiary: 'Saudi Arabia Subsidiary',
      region: 'MEA (Middle East & Africa)',
      description: 'Launch digital wallet with P2P payments, bill pay, and merchant integration for mobile-first customers.',
      industry: 'banking' as Industry,
      solutionArea: 'AI Business Solutions' as SolutionArea,
      investmentAmount: 1850000,
      timelineMonths: 16,
    },
    baselineMetrics: {
      currentRevenue: 45000000,
      currentCosts: 22000000,
      employeeCount: 450,
      currentAssets: 120000000,
      currentCashFlow: 18000000,
    },
    impactProjections: {
      revenueGrowthRate: 32,
      costReduction: 15,
      efficiencyGain: 28,
      timeToMarketImprovement: 25,
    },
    strategicFactors: {
      competitiveDifferentiation: 5,
      riskMitigation: 4,
      customerExperience: 5,
      employeeProductivity: 3,
      regulatoryCompliance: 4,
      innovationEnablement: 5,
    },
    results: {
      conservative: {
        roi: 255,
        npv: 4717500,
        paybackMonths: 9.8,
        revenueImpact: 14400000,
        costSavings: 3300000,
        netBenefit: 15850000,
      },
      realistic: {
        roi: 319,
        npv: 5902500,
        paybackMonths: 7.8,
        revenueImpact: 14400000,
        costSavings: 3300000,
        netBenefit: 15850000,
      },
      optimistic: {
        roi: 382,
        npv: 7069500,
        paybackMonths: 6.5,
        revenueImpact: 14400000,
        costSavings: 3300000,
        netBenefit: 15850000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'critical' as Priority,
      reasoning: 'Exceptional growth opportunity in mobile-first market. Strong competitive positioning and customer engagement.',
      nextSteps: [
        'Obtain regulatory approvals',
        'Select payment gateway partners',
        'Design user onboarding flow',
      ],
      successMetrics: [
        'Active wallet users > 500K in year 1',
        'Transaction volume $100M+ monthly',
        'Merchant acceptance at 10K+ locations',
      ],
      risks: [
        'Regulatory compliance complexity',
        'Competition from global players',
        'Security and fraud management',
      ],
    },
  },
  {
    id: 'seed-17',
    createdAt: Date.now() - 86400000 * 35,
    updatedAt: Date.now() - 86400000 * 35,
    projectBasics: {
      name: 'Smart Warehouse Automation',
      customerName: 'AutoManufacture Corp',
      subsidiary: 'Norway Subsidiary',
      region: 'North Europe',
      description: 'Automated guided vehicles, robotic picking, and AI-driven warehouse management for faster fulfillment.',
      industry: 'manufacturing' as Industry,
      solutionArea: 'AI Business Solutions' as SolutionArea,
      investmentAmount: 3500000,
      timelineMonths: 20,
    },
    baselineMetrics: {
      currentRevenue: 120000000,
      currentCosts: 85000000,
      employeeCount: 850,
      currentAssets: 250000000,
      currentCashFlow: 28000000,
    },
    impactProjections: {
      revenueGrowthRate: 10,
      costReduction: 30,
      efficiencyGain: 45,
      timeToMarketImprovement: 20,
    },
    strategicFactors: {
      competitiveDifferentiation: 4,
      riskMitigation: 4,
      customerExperience: 4,
      employeeProductivity: 5,
      regulatoryCompliance: 3,
      innovationEnablement: 4,
    },
    results: {
      conservative: {
        roi: 178,
        npv: 6230000,
        paybackMonths: 13.2,
        revenueImpact: 12000000,
        costSavings: 25500000,
        netBenefit: 34000000,
      },
      realistic: {
        roi: 223,
        npv: 7805000,
        paybackMonths: 10.5,
        revenueImpact: 12000000,
        costSavings: 25500000,
        netBenefit: 34000000,
      },
      optimistic: {
        roi: 267,
        npv: 9345000,
        paybackMonths: 8.8,
        revenueImpact: 12000000,
        costSavings: 25500000,
        netBenefit: 34000000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'high' as Priority,
      reasoning: 'Strong cost savings and efficiency gains. Positions for future growth and scalability.',
      nextSteps: [
        'Design warehouse layout optimization',
        'Select automation vendors',
        'Plan phased deployment approach',
      ],
      successMetrics: [
        'Order fulfillment time reduced by 60%',
        'Picking accuracy > 99.8%',
        'Labor costs reduced by 35%',
      ],
      risks: [
        'High capital investment requirement',
        'Integration with existing systems',
        'Workforce transition management',
      ],
    },
  },
  {
    id: 'seed-18',
    createdAt: Date.now() - 86400000 * 40,
    updatedAt: Date.now() - 86400000 * 40,
    projectBasics: {
      name: 'API Marketplace Platform',
      customerName: 'TechVentures Ltd',
      subsidiary: 'Brazil Subsidiary',
      region: 'Americas',
      description: 'Developer portal and API marketplace to monetize internal capabilities and foster ecosystem growth.',
      industry: 'technology' as Industry,
      solutionArea: 'Cloud & AI Platforms' as SolutionArea,
      investmentAmount: 650000,
      timelineMonths: 13,
    },
    baselineMetrics: {
      currentRevenue: 28000000,
      currentCosts: 19000000,
      employeeCount: 185,
      currentAssets: 45000000,
      currentCashFlow: 7500000,
    },
    impactProjections: {
      revenueGrowthRate: 35,
      costReduction: 8,
      efficiencyGain: 22,
      timeToMarketImprovement: 40,
    },
    strategicFactors: {
      competitiveDifferentiation: 5,
      riskMitigation: 3,
      customerExperience: 4,
      employeeProductivity: 4,
      regulatoryCompliance: 3,
      innovationEnablement: 5,
    },
    results: {
      conservative: {
        roi: 425,
        npv: 2762500,
        paybackMonths: 5.9,
        revenueImpact: 9800000,
        costSavings: 1520000,
        netBenefit: 10670000,
      },
      realistic: {
        roi: 531,
        npv: 3451500,
        paybackMonths: 4.7,
        revenueImpact: 9800000,
        costSavings: 1520000,
        netBenefit: 10670000,
      },
      optimistic: {
        roi: 638,
        npv: 4147000,
        paybackMonths: 3.9,
        revenueImpact: 9800000,
        costSavings: 1520000,
        netBenefit: 10670000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'critical' as Priority,
      reasoning: 'Exceptional growth potential through new revenue streams. Creates platform ecosystem and developer community.',
      nextSteps: [
        'Define API product catalog',
        'Build developer portal',
        'Establish pricing and monetization model',
      ],
      successMetrics: [
        'Developer registrations > 5,000',
        'API call volume > 50M monthly',
        'Partner integrations > 200',
      ],
      risks: [
        'API product-market fit',
        'Developer adoption and engagement',
        'Security and rate limiting',
      ],
    },
  },
  {
    id: 'seed-19',
    createdAt: Date.now() - 86400000 * 42,
    updatedAt: Date.now() - 86400000 * 42,
    projectBasics: {
      name: 'Augmented Reality Shopping',
      customerName: 'RetailGlobal Inc',
      subsidiary: 'Portugal Subsidiary',
      region: 'South Europe',
      description: 'AR-enabled mobile app for virtual try-on and product visualization in customer environments.',
      industry: 'retail' as Industry,
      solutionArea: 'AI Business Solutions' as SolutionArea,
      investmentAmount: 1250000,
      timelineMonths: 15,
    },
    baselineMetrics: {
      currentRevenue: 95000000,
      currentCosts: 62000000,
      employeeCount: 620,
      currentAssets: 85000000,
      currentCashFlow: 24000000,
    },
    impactProjections: {
      revenueGrowthRate: 38,
      costReduction: 10,
      efficiencyGain: 25,
      timeToMarketImprovement: 15,
    },
    strategicFactors: {
      competitiveDifferentiation: 5,
      riskMitigation: 2,
      customerExperience: 5,
      employeeProductivity: 3,
      regulatoryCompliance: 2,
      innovationEnablement: 5,
    },
    results: {
      conservative: {
        roi: 398,
        npv: 4975000,
        paybackMonths: 6.2,
        revenueImpact: 36100000,
        costSavings: 6200000,
        netBenefit: 41050000,
      },
      realistic: {
        roi: 498,
        npv: 6225000,
        paybackMonths: 5.0,
        revenueImpact: 36100000,
        costSavings: 6200000,
        netBenefit: 41050000,
      },
      optimistic: {
        roi: 597,
        npv: 7462500,
        paybackMonths: 4.2,
        revenueImpact: 36100000,
        costSavings: 6200000,
        netBenefit: 41050000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'critical' as Priority,
      reasoning: 'Game-changing customer experience with exceptional revenue potential. Major competitive differentiator.',
      nextSteps: [
        'Develop AR technology stack',
        'Create 3D product catalog',
        'Design intuitive user interface',
      ],
      successMetrics: [
        'AR feature usage by 40% of app users',
        'Conversion rate up 55%',
        'Return rate reduced by 30%',
      ],
      risks: [
        'Technical complexity and device support',
        'Content creation workload',
        'User adoption and learning curve',
      ],
    },
  },
  {
    id: 'seed-20',
    createdAt: Date.now() - 86400000 * 45,
    updatedAt: Date.now() - 86400000 * 45,
    projectBasics: {
      name: 'Open Banking Integration',
      customerName: 'FirstBank International',
      subsidiary: 'Kuwait Subsidiary',
      region: 'MEA (Middle East & Africa)',
      description: 'Open banking API platform for third-party integrations, enabling new revenue streams and partnerships.',
      industry: 'banking' as Industry,
      solutionArea: 'Cloud & AI Platforms' as SolutionArea,
      investmentAmount: 1450000,
      timelineMonths: 17,
    },
    baselineMetrics: {
      currentRevenue: 45000000,
      currentCosts: 22000000,
      employeeCount: 450,
      currentAssets: 120000000,
      currentCashFlow: 18000000,
    },
    impactProjections: {
      revenueGrowthRate: 22,
      costReduction: 12,
      efficiencyGain: 20,
      timeToMarketImprovement: 35,
    },
    strategicFactors: {
      competitiveDifferentiation: 4,
      riskMitigation: 3,
      customerExperience: 5,
      employeeProductivity: 3,
      regulatoryCompliance: 5,
      innovationEnablement: 5,
    },
    results: {
      conservative: {
        roi: 188,
        npv: 2726000,
        paybackMonths: 12.5,
        revenueImpact: 9900000,
        costSavings: 2640000,
        netBenefit: 11090000,
      },
      realistic: {
        roi: 235,
        npv: 3407500,
        paybackMonths: 10.0,
        revenueImpact: 9900000,
        costSavings: 2640000,
        netBenefit: 11090000,
      },
      optimistic: {
        roi: 282,
        npv: 4089000,
        paybackMonths: 8.3,
        revenueImpact: 9900000,
        costSavings: 2640000,
        netBenefit: 11090000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'high' as Priority,
      reasoning: 'Strategic necessity for regulatory compliance with strong revenue potential. Enables ecosystem growth.',
      nextSteps: [
        'Ensure regulatory compliance',
        'Design API security framework',
        'Recruit partner ecosystem',
      ],
      successMetrics: [
        'Active third-party integrations > 50',
        'API transaction volume > 10M monthly',
        'Partner-driven revenue > $5M annually',
      ],
      risks: [
        'Security and fraud concerns',
        'Regulatory changes',
        'Partner quality and reliability',
      ],
    },
  },
  {
    id: 'seed-21',
    createdAt: Date.now() - 86400000 * 48,
    updatedAt: Date.now() - 86400000 * 48,
    projectBasics: {
      name: 'Sustainability Analytics Platform',
      customerName: 'AutoManufacture Corp',
      subsidiary: 'Denmark Subsidiary',
      region: 'North Europe',
      description: 'ESG tracking and reporting platform for carbon footprint, resource usage, and sustainability metrics.',
      industry: 'manufacturing' as Industry,
      solutionArea: 'Cloud & AI Platforms' as SolutionArea,
      investmentAmount: 980000,
      timelineMonths: 12,
    },
    baselineMetrics: {
      currentRevenue: 120000000,
      currentCosts: 85000000,
      employeeCount: 850,
      currentAssets: 250000000,
      currentCashFlow: 28000000,
    },
    impactProjections: {
      revenueGrowthRate: 8,
      costReduction: 18,
      efficiencyGain: 25,
      timeToMarketImprovement: 8,
    },
    strategicFactors: {
      competitiveDifferentiation: 4,
      riskMitigation: 5,
      customerExperience: 3,
      employeeProductivity: 3,
      regulatoryCompliance: 5,
      innovationEnablement: 3,
    },
    results: {
      conservative: {
        roi: 195,
        npv: 1911000,
        paybackMonths: 11.8,
        revenueImpact: 9600000,
        costSavings: 15300000,
        netBenefit: 23920000,
      },
      realistic: {
        roi: 244,
        npv: 2391200,
        paybackMonths: 9.4,
        revenueImpact: 9600000,
        costSavings: 15300000,
        netBenefit: 23920000,
      },
      optimistic: {
        roi: 293,
        npv: 2871400,
        paybackMonths: 7.8,
        revenueImpact: 9600000,
        costSavings: 15300000,
        netBenefit: 23920000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'high' as Priority,
      reasoning: 'Critical for regulatory compliance and stakeholder expectations. Enables sustainability-driven cost savings.',
      nextSteps: [
        'Define ESG metrics and KPIs',
        'Integrate IoT sensors for data collection',
        'Design reporting dashboards',
      ],
      successMetrics: [
        'Carbon emissions reduced by 25%',
        'Regulatory reporting automated',
        'ESG score improved to top quartile',
      ],
      risks: [
        'Data collection and accuracy',
        'Changing regulatory requirements',
        'Integration with operational systems',
      ],
    },
  },
  {
    id: 'seed-22',
    createdAt: Date.now() - 86400000 * 50,
    updatedAt: Date.now() - 86400000 * 50,
    projectBasics: {
      name: 'Voice Commerce Platform',
      customerName: 'RetailGlobal Inc',
      subsidiary: 'Greece Subsidiary',
      region: 'South Europe',
      description: 'Voice-activated shopping through smart speakers and voice assistants with AI-powered recommendations.',
      industry: 'retail' as Industry,
      solutionArea: 'AI Business Solutions' as SolutionArea,
      investmentAmount: 580000,
      timelineMonths: 11,
    },
    baselineMetrics: {
      currentRevenue: 95000000,
      currentCosts: 62000000,
      employeeCount: 620,
      currentAssets: 85000000,
      currentCashFlow: 24000000,
    },
    impactProjections: {
      revenueGrowthRate: 18,
      costReduction: 8,
      efficiencyGain: 15,
      timeToMarketImprovement: 20,
    },
    strategicFactors: {
      competitiveDifferentiation: 5,
      riskMitigation: 2,
      customerExperience: 5,
      employeeProductivity: 2,
      regulatoryCompliance: 3,
      innovationEnablement: 5,
    },
    results: {
      conservative: {
        roi: 348,
        npv: 2018400,
        paybackMonths: 7.2,
        revenueImpact: 17100000,
        costSavings: 4960000,
        netBenefit: 21480000,
      },
      realistic: {
        roi: 435,
        npv: 2523000,
        paybackMonths: 5.8,
        revenueImpact: 17100000,
        costSavings: 4960000,
        netBenefit: 21480000,
      },
      optimistic: {
        roi: 522,
        npv: 3027600,
        paybackMonths: 4.8,
        revenueImpact: 17100000,
        costSavings: 4960000,
        netBenefit: 21480000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'high' as Priority,
      reasoning: 'Innovative channel with strong growth potential. Early mover advantage in emerging commerce platform.',
      nextSteps: [
        'Integrate with major voice platforms',
        'Design conversational commerce flows',
        'Optimize product catalog for voice',
      ],
      successMetrics: [
        'Voice commerce orders > 5% of total',
        'Voice order conversion rate > 25%',
        'Customer satisfaction > 4.6/5',
      ],
      risks: [
        'Platform dependency (Alexa, Google)',
        'Voice recognition accuracy',
        'User adoption and behavior change',
      ],
    },
  },
  {
    id: 'seed-23',
    createdAt: Date.now() - 86400000 * 52,
    updatedAt: Date.now() - 86400000 * 52,
    projectBasics: {
      name: 'Blockchain Trade Finance',
      customerName: 'FirstBank International',
      subsidiary: 'Ireland Subsidiary',
      region: 'North Europe',
      description: 'Blockchain-based trade finance platform for letter of credit, invoice financing, and supply chain finance.',
      industry: 'banking' as Industry,
      solutionArea: 'AI Business Solutions' as SolutionArea,
      investmentAmount: 2200000,
      timelineMonths: 20,
    },
    baselineMetrics: {
      currentRevenue: 45000000,
      currentCosts: 22000000,
      employeeCount: 450,
      currentAssets: 120000000,
      currentCashFlow: 18000000,
    },
    impactProjections: {
      revenueGrowthRate: 15,
      costReduction: 25,
      efficiencyGain: 38,
      timeToMarketImprovement: 30,
    },
    strategicFactors: {
      competitiveDifferentiation: 5,
      riskMitigation: 5,
      customerExperience: 4,
      employeeProductivity: 4,
      regulatoryCompliance: 4,
      innovationEnablement: 5,
    },
    results: {
      conservative: {
        roi: 142,
        npv: 3124000,
        paybackMonths: 16.5,
        revenueImpact: 6750000,
        costSavings: 5500000,
        netBenefit: 10050000,
      },
      realistic: {
        roi: 178,
        npv: 3916000,
        paybackMonths: 13.2,
        revenueImpact: 6750000,
        costSavings: 5500000,
        netBenefit: 10050000,
      },
      optimistic: {
        roi: 213,
        npv: 4686000,
        paybackMonths: 11.0,
        revenueImpact: 6750000,
        costSavings: 5500000,
        netBenefit: 10050000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'high' as Priority,
      reasoning: 'Strategic innovation in trade finance with strong efficiency and transparency benefits. Competitive advantage.',
      nextSteps: [
        'Build consortium with trade partners',
        'Select blockchain platform',
        'Design smart contract templates',
      ],
      successMetrics: [
        'Transaction processing time reduced by 70%',
        'Document verification automated',
        'Partner network > 100 institutions',
      ],
      risks: [
        'Consortium building complexity',
        'Regulatory uncertainty',
        'Technology maturity concerns',
      ],
    },
  },
  {
    id: 'seed-24',
    createdAt: Date.now() - 86400000 * 55,
    updatedAt: Date.now() - 86400000 * 55,
    projectBasics: {
      name: 'AI-Powered Pricing Optimization',
      customerName: 'RetailGlobal Inc',
      subsidiary: 'Israel Subsidiary',
      region: 'South Europe',
      description: 'Dynamic pricing engine using AI to optimize prices based on demand, competition, and inventory levels.',
      industry: 'retail' as Industry,
      solutionArea: 'AI Business Solutions' as SolutionArea,
      investmentAmount: 820000,
      timelineMonths: 10,
    },
    baselineMetrics: {
      currentRevenue: 95000000,
      currentCosts: 62000000,
      employeeCount: 620,
      currentAssets: 85000000,
      currentCashFlow: 24000000,
    },
    impactProjections: {
      revenueGrowthRate: 15,
      costReduction: 12,
      efficiencyGain: 22,
      timeToMarketImprovement: 15,
    },
    strategicFactors: {
      competitiveDifferentiation: 4,
      riskMitigation: 3,
      customerExperience: 4,
      employeeProductivity: 4,
      regulatoryCompliance: 3,
      innovationEnablement: 4,
    },
    results: {
      conservative: {
        roi: 288,
        npv: 2361600,
        paybackMonths: 8.5,
        revenueImpact: 14250000,
        costSavings: 7440000,
        netBenefit: 20870000,
      },
      realistic: {
        roi: 360,
        npv: 2952000,
        paybackMonths: 6.8,
        revenueImpact: 14250000,
        costSavings: 7440000,
        netBenefit: 20870000,
      },
      optimistic: {
        roi: 432,
        npv: 3542400,
        paybackMonths: 5.7,
        revenueImpact: 14250000,
        costSavings: 7440000,
        netBenefit: 20870000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'critical' as Priority,
      reasoning: 'Exceptional margin improvement with quick payback. Critical for competitive pricing strategy.',
      nextSteps: [
        'Integrate competitive intelligence feeds',
        'Train pricing algorithms',
        'Pilot in select categories',
      ],
      successMetrics: [
        'Gross margin improved by 3.5%',
        'Price optimization coverage > 80% of SKUs',
        'Promotional effectiveness up 40%',
      ],
      risks: [
        'Customer perception of fairness',
        'Competitive response',
        'Algorithm transparency requirements',
      ],
    },
  },
  {
    id: 'seed-25',
    createdAt: Date.now() - 86400000 * 58,
    updatedAt: Date.now() - 86400000 * 58,
    projectBasics: {
      name: 'Cybersecurity Operations Center',
      customerName: 'TechVentures Ltd',
      subsidiary: 'Mexico Subsidiary',
      region: 'Americas',
      description: '24/7 security operations center with SIEM, threat intelligence, and incident response capabilities.',
      industry: 'technology' as Industry,
      solutionArea: 'Security' as SolutionArea,
      investmentAmount: 1350000,
      timelineMonths: 14,
    },
    baselineMetrics: {
      currentRevenue: 28000000,
      currentCosts: 19000000,
      employeeCount: 185,
      currentAssets: 45000000,
      currentCashFlow: 7500000,
    },
    impactProjections: {
      revenueGrowthRate: 5,
      costReduction: 22,
      efficiencyGain: 30,
      timeToMarketImprovement: 10,
    },
    strategicFactors: {
      competitiveDifferentiation: 3,
      riskMitigation: 5,
      customerExperience: 3,
      employeeProductivity: 4,
      regulatoryCompliance: 5,
      innovationEnablement: 3,
    },
    results: {
      conservative: {
        roi: 125,
        npv: 1687500,
        paybackMonths: 17.8,
        revenueImpact: 1400000,
        costSavings: 4180000,
        netBenefit: 4230000,
      },
      realistic: {
        roi: 156,
        npv: 2106000,
        paybackMonths: 14.2,
        revenueImpact: 1400000,
        costSavings: 4180000,
        netBenefit: 4230000,
      },
      optimistic: {
        roi: 188,
        npv: 2538000,
        paybackMonths: 11.8,
        revenueImpact: 1400000,
        costSavings: 4180000,
        netBenefit: 4230000,
      },
    },
    recommendation: {
      decision: 'go',
      priority: 'critical' as Priority,
      reasoning: 'Essential for risk mitigation and compliance. Prevents costly breaches and protects brand reputation.',
      nextSteps: [
        'Design SOC architecture',
        'Select SIEM platform',
        'Hire security analysts',
      ],
      successMetrics: [
        'Mean time to detect < 15 minutes',
        'Mean time to respond < 1 hour',
        'Zero successful breaches',
      ],
      risks: [
        'Talent acquisition and retention',
        'Alert fatigue and false positives',
        'Integration complexity',
      ],
    },
  },
]
